databases:
  - name: default
    plan: free
    databaseName: chatpdf
    user: dbmaster

services:
  - type: web
    plan: free
    name: EducacionChat
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn EducacionChat.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: "ChatPDF_DATABASE"
        fromDatabase:
          name: chatpdf
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4